[package]
name = "meowjelly"
version = "1.0.0"
edition = "2021"

[profile.dev.package."*"]
opt-level = 2

[dependencies]
geng.git = "https://github.com/kuviman/geng"
serde = "1"

[patch.crates-io]
# https://github.com/smol-rs/async-broadcast/pull/47
async-broadcast = {git = "https://github.com/kuviman/async-broadcast", branch = "fix-wasm"}
