tube_radius = 10
wall_section = 10

[shadow]
distance = 7.5
scale = 2
alpha = 0.3

[player]
max_speed = 30
acceleration = 300
fall_speed = 100
fall_acceleration = 10
radius = 1
bounce_speed = 75

[touch_control]
max_speed = 60
small_radius = 3
big_radius = 10

[camera]
horizontal_movement = 0.5
distance = 10
acceleration = 10
