start_time = 0.5
tube_radius = 10
wall_section = 10
bounce_particles = 10
bounce_particle_speed = 10
death_distance = 2

[tutorial]
scale = 0.015
touch_pos = [0, -1.5, 0]
keyboard_pos = [0, 2, 0]

[obstacles]
distance = { min = 50, max = 150 }

[legs]
length = 0.7
wiggle = 0.04
freq = 2
z = 0.3
rotate_speed = 360

[shake]
time = 0.3
amount = 2
freq = 60

[shadow]
distance = 9.5
scale = 4
alpha = 0.6

[player]
max_speed = 30
acceleration = 300
fall_speed = 100
fall_acceleration = 10
radius = 1
bounce_speed = 50
bounce_time = 2
rotate_angle = 45
particle_speed_ratio = 0.0

[passive_rotation]
speed = 0
amplitude = 10
frequency = 0.5

[touch_control]
max_speed = 60
small_radius = 3
big_radius = 10

[camera]
horizontal_movement = 0.5
distance = 10
acceleration = 40
fov = 70
start_fov = 30
