[movement]
freq = 20
life = 0.1
size = 0.3
color = "#f0f0"
extra_vel = 1
extra_life = 0.1
extra_size = 0.8
extra_hue = 0.2
extra_saturation = 0.1
extra_lightness = 0.1

[bounce]
freq = 40
life = 0.5
size = 0.7
color = "#5557"
extra_vel = 5
extra_life = 0.5
extra_size = 1
extra_hue = 0.1
extra_saturation = 0.1
extra_lightness = 0.1

[death]
freq = 40
life = 0.5
size = 0.7
color = "#fff7"
extra_vel = 5
extra_life = 0.5
extra_size = 1
extra_hue = 0.1
extra_saturation = 0.1
extra_lightness = 0.1
